# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-ecr: circleci/aws-ecr@8.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:2022.08

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    working_directory: ~/nightout

    steps:
      - flutter/install_sdk:
          version: 3.3.0
      - checkout
      - run:
          name: Build Web
          working_directory: ~/nightout
          command: flutter build web --web-renderer=canvaskit
      - persist_to_workspace:
          root: .
          paths:
            - build
            - Dockerfile

parameters:
  image-tag: 
    type: string
    default: ${CIRCLE_SHA1}
  web-build-and-deploy: 
    type: boolean
    default: true
  web-deploy: 
    type: boolean
    default: false
  
  

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  web-deploy:
    when: << pipeline.parameters.web-deploy >>
    jobs:
      - aws-ecs/deploy-service-update:
          cluster: nightout
          family: nightout-web
          container-image-name-updates: container=web,tag=<< pipeline.parameters.image-tag >>

  web-build-and-deploy:
    when: << pipeline.parameters.web-build-and-deploy >>
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          requires: 
            - build
          repo: nightout
          tag: '${CIRCLE_SHA1}'
          attach-workspace: true
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          cluster: nightout
          family: web
          container-image-name-updates: container=web,tag=<< pipeline.parameters.image-tag >>
